### ISSUE TITLE
cant get the pdf document using the contentStorageId

### ISSUE THREAD

**Issue by mehdi-kettani** [Bonitasoft-Community/PDF-viewer-widget#1]
Hello Philippe,

After a quick test, i could not get the pdf and display it using the contentStorageId. however, i was able to do it using document id.

bonita version used is 7.2.0

Can you take a look, and update documentation accordingly.

Thanks,

Mehdi

**Comment by pozil** [comment]
Hi Mehdi,

I did a quick test with the provided example process (Display PDF) and version 7.2.0 and 7.2.1 and both work fine.
Can you share more information on the test you did?

Cheers,

**Comment by amottier** [comment]
Bonita file widget is available in Bonita Community Edition 7.9 so we will not provide help on this community contribution widget.
Please try the file viewer widget and report issues on https://bonita.atlassian.net/projects/BBPMC/issues if you find any.
