### ISSUE TITLE
PDFviewer Returned HTTP 500 error after Document Updating

### ISSUE THREAD

**Issue by hendrasuparmo** [Bonitasoft-Community/PDF-viewer-widget#2]
Dear Sir

We did a project with Bonita 7.4.3 community edition and implemented PDFviewer widget from
https://github.com/Bonitasoft-Community/PDF-viewer-widget

It worked well until we implemented the document update method from
https://github.com/Bonitasoft-Community/file-upload-download-example

then all document viewed from PDFviewer widget returned http 500 error.

May we raise an issue for the matter, your help would be appreciated. Thank you very much for attention.

Best regards

**Comment by amottier** [comment]
Bonita file widget is available in Bonita Community Edition 7.9 so we will not provide help on this community contribution widget.
Please try the file viewer widget and report issues on https://bonita.atlassian.net/projects/BBPMC/issues if you find any.
