### ISSUE TITLE
problema de ver pdf

### ISSUE THREAD

**Issue by ralikhan** [Bonitasoft-Community/PDF-viewer-widget#3]
Hello. good afternoon. I'm trying to use pdf viewer in my project but I do not get it, I do not know how to do it. please, can you help me. thank you.

![1](https://user-images.githubusercontent.com/39272051/47581297-4f406a00-d951-11e8-8fe1-12b9f82b521d.png)
![2](https://user-images.githubusercontent.com/39272051/47581309-55364b00-d951-11e8-970a-d57bed39aeee.png)

**Comment by ralikhan** [comment]
I have used your widget but it also does not show pdf. I have tried many ways but I do not get it. please, can you help me.

[pdf.zip](https://github.com/Bonitasoft-Community/PDF-viewer-widget/files/2524676/pdf.zip)

**Comment by amottier** [comment]
Bonita file widget is available in Bonita Community Edition 7.9 so we will not provide help on this community contribution widget.
Please try the file viewer widget and report issues on https://bonita.atlassian.net/projects/BBPMC/issues if you find any.
